services:
    client:
        container_name: rserba-client
        image: riyanamanda/rserba-client:1.0.0
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped

    database:
        container_name: rserba-database
        image: postgres:17.5
        ports:
          - 5432:5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        restart: unless-stopped
        volumes:
          - ./data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    server:
        container_name: rserba-server
        image: riyanamanda/rserba-server:1.0.0
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            database:
                condition: service_healthy
        restart: unless-stopped