spring:
    servlet:
        multipart:
            max-file-size: 10MB
    profiles:
        active: ${ACTIVE_PROFILE:dev}
    datasource:
        url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: false
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
        generate-ddl: true
        show-sql: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    flyway:
        enabled: true
        locations: classpath:db/migrations

server:
    servlet:
        context-path: /api/

project:
    doctor_image: server/images/doctor/
base:
    url: ${BASE_URL}